### ISSUE TITLE
Change Input Text

### ISSUE THREAD

**Issue by ArcadeRenegade** [crabstudio/react-native-search-box#10]
Hi, is there any way to change the current input text of the search programatically?

**Comment by anhtuank7c** [comment]
@ArcadeRenegade 
What kind of current input text?
Read this example: https://github.com/crabstudio/react-native-atoz-listview/blob/master/example/src/screens/Contacts/Home.js#L67

**Comment by ArcadeRenegade** [comment]
Well, to be specific, I wanted to use RegEx to only allow certain types of characters in the search input.

**Comment by anhtuank7c** [comment]
You must have search bar `ref`, then you can reference to the input and do validate regex in `onChangeText`.

**Comment by ArcadeRenegade** [comment]
Okay I will give it a try. Thanks!
