### ISSUE TITLE
React.createElement: type is invalid

### ISSUE THREAD

**Issue by Javis1205** [crabstudio/react-native-search-box#2]
I encountered this error while using :

W/ReactNativeJS( 7420): Warning: React.createElement: type is invalid -- expecte d a string (for built-in components) or a class/function (for composite componen ts) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `StaticRenderer`.

**Comment by anhtuank7c** [comment]
Ensure that you install latest version: 0.0.3
Make a gist for your code please.

**Comment by anhtuank7c** [comment]
@Javis1205 
Did you resolved it?
Seem you enter wrong props type than my module contain error.

Should we close this issue?
