### ISSUE TITLE
Make cancel text optional

### ISSUE THREAD

**Issue by 0x6e6562** [crabstudio/react-native-search-box#6]
This is a really cool component - is there a way to disable the cancel text and it's associated functionality so that the search box just has the search icon and the clear icon?

**Comment by anhtuank7c** [comment]
@0x6e6562 No, it isn't.
See https://github.com/crabstudio/react-native-search-box/blob/master/index.js#L305
I'll think about it.

**Comment by 0x6e6562** [comment]
@anhtuank7c Thanks for the heads up :-)

I'll close this issue now.
